apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: main
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: singleton
  labels:
    special: singleton
spec:
  replicas: 1
  selector:
    matchLabels:
      special: singleton
  template:
    metadata:
      labels:
        special: singleton
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
