# ESCluster is depended by ESBackup and ESRestore.
apiVersion: elasticsearch.cloud.google.com/v1alpha1
kind: ESCluster
metadata:
  name: esbasic
spec:
  plugin:
   pluginList:
    - repository-gcs
    - ingest-user-agent
    - ingest-geoip
  # To set `gcpserviceaccount`,
  # First, create and download a GCP service account into a json file, named `sakey.json` following the instruction:
  #     https://www.elastic.co/guide/en/elasticsearch/plugins/6.5/repository-gcs-usage.html#repository-gcs-using-service-account
  # Second, create a secret for the service account using the following command:
  #     $ kubectl create secret generic kustomizesa --from-file=./sakey.json
  gcpserviceaccount:
    name: kustomizesa
  config:
    env:
      example: test
  nodegroups:
    - name: di
      replicas: 2
      data: true
      ingest: true
      config:
        jvm:
          - Djava.net.preferIPv4Stack=true
          - Xms2g
          - Xmx2g
        es:
          path.repo: '["/tmp/es_backup_basic"]'
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                es/nodegroup: di
      resources:
        requests:
          memory: 3Gi
        limits:
          memory: 3Gi
    - name: m
      replicas: 2
      master: true
      config:
        es:
          path.repo: '["/tmp/es_backup_basic"]'
